// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0NiObSDKSs8lzS4A0mH07g-64T128_U',
    appId: '1:109352699072:web:36a6b9b5c8da96c1905925',
    messagingSenderId: '109352699072',
    projectId: 'feedbackhub-bd790',
    authDomain: 'feedbackhub-bd790.firebaseapp.com',
    storageBucket: 'feedbackhub-bd790.firebasestorage.app',
    measurementId: 'G-ZRHDC7K1J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtVQow65DEgxWjg445KC4XNDUppOFLqwc',
    appId: '1:109352699072:android:20d5c5cb1a87c7e3905925',
    messagingSenderId: '109352699072',
    projectId: 'feedbackhub-bd790',
    storageBucket: 'feedbackhub-bd790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEBY6I3EnGuXFHbov7RIiGz485PvUf-A',
    appId: '1:109352699072:ios:1df5990cc7eef055905925',
    messagingSenderId: '109352699072',
    projectId: 'feedbackhub-bd790',
    storageBucket: 'feedbackhub-bd790.firebasestorage.app',
    iosBundleId: 'com.example.govFeedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXEBY6I3EnGuXFHbov7RIiGz485PvUf-A',
    appId: '1:109352699072:ios:1df5990cc7eef055905925',
    messagingSenderId: '109352699072',
    projectId: 'feedbackhub-bd790',
    storageBucket: 'feedbackhub-bd790.firebasestorage.app',
    iosBundleId: 'com.example.govFeedbackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0NiObSDKSs8lzS4A0mH07g-64T128_U',
    appId: '1:109352699072:web:6d23e697020f59c3905925',
    messagingSenderId: '109352699072',
    projectId: 'feedbackhub-bd790',
    authDomain: 'feedbackhub-bd790.firebaseapp.com',
    storageBucket: 'feedbackhub-bd790.firebasestorage.app',
    measurementId: 'G-5JGFC2R6TM',
  );
}
